action:
- name: Fernseher_lauter
  actions:
  - keyword: resources/Fernseher_lauter.pmdl
  - endpoint: http://192.168.8.131:5000/api/function/fernseher/lauter
  - httpmethod: GET
  - bodyData: x
- name: Fernseher_aus
  actions:
  - keyword: resources/Fernseher_aus.pmdl
  - endpoint: http://192.168.8.131:5000/api/function/fernseher/aus
  - httpmethod: GET
  - bodyData: x
