#die folgende Konfiguration besteht aus_
#Zwei Elemente in der ersten Ebene: Wohnzimmer und Esszimmer
#Bei Wohnzimmer gibt es ein Unterlevel mit einem Element "Licht", dass ein und ausgeschaltet werden kann
#Esszimmer hat eine Unterebene mit 2 Elementen: "Deckenlicht" und "Stehlampe", die wieder in einem eigenen Unterlevel ein- bzw. ausgeschaltet werden können.

configuration:
- name: Wohnzimmer
  keywords:
  - keyword: resources/Wohnzimmer.pmdl
    actions:
      echo: selected Wohnzimmer!
      sublevel:
      - name: Licht
        keywords:
        - keyword: resources/Licht.pmdl
          actions:
            echo: Wohnzimmer - Licht selected!
            sublevel:
            - name: einschalten
              keywords:
              - keyword: resources/einschalten.pmdl
                actions:
                  echo: Licht eingeschaltet!
            - name: ausschalten
              keywords:
              - keyword: resources/ausschalten.pmdl
                actions:
                  echo: Licht ausgeschaltet!
      - name: Fernseher
        keywords:
        - keyword: resources/Fernseher.pmdl
          actions:
            echo: Wohnzimmer - Fernseher selected!
            sublevel:
            - name: einschalten
              keywords:
              - keyword: resources/einschalten.pmdl
                actions:
                  echo: Fernseher eingeschaltet!
            - name: ausschalten
              keywords:
              - keyword: resources/ausschalten.pmdl
                actions:
                  echo: Fernseher ausgeschaltet!
            - name: lauter
              keywords:
              - keyword: resources/Lauter.pmdl
                actions:
                  echo: Fernseher lauter!
            - name: leiser
              keywords:
              - keyword: resources/Leiser.pmdl
                actions:
                  echo: Fernseher leiser!
      - name: Rollo
        keywords:
        - keyword: resources/Rollo.pmdl
          actions:
            echo: Wohnzimmer - Rollo selected!
            sublevel:
            - name: einschalten
              keywords:
              - keyword: resources/Hoch.pmdl
                actions:
                  echo: Rollo hoch!
            - name: ausschalten
              keywords:
              - keyword: resources/Runter.pmdl
                actions:
                  echo: Rollo runter!
- name: Esszimmer
  keywords:
  - keyword: resources/Esszimmer.pmdl
    actions:
      echo: selected Esszimmer!
      sublevel:
      - name: Licht
        keywords:
        - keyword: resources/Licht.pmdl
          actions:
            echo: Esszimmer - Licht selected!
            sublevel:
            - name: einschalten
              keywords:
              - keyword: resources/einschalten.pmdl
                actions:
                  echo: Licht eingeschaltet!
            - name: ausschalten
              keywords:
              - keyword: resources/ausschalten.pmdl
                actions:
                  echo: Licht ausgeschaltet!
- name: Kueche
  keywords:
  - keyword: resources/Kueche.pmdl
    actions:
      echo: selected Kueche
      sublevel:
      - name: Licht
        keywords:
        - keyword: resources/Licht.pmdl
          actions:
            echo: Kueche - Licht selected!
            sublevel:
            - name: einschalten
              keywords:
              - keyword: resources/einschalten.pmdl
                actions:
                  echo: Licht eingeschaltet!
            - name: ausschalten
              keywords:
              - keyword: resources/ausschalten.pmdl
                actions:
                  echo: Licht ausgeschaltet!
- name: Schlafzimmer
  keywords:
  - keyword: resources/Schlafzimmer.pmdl
    actions:
      echo: selected Schlafzimmer
      sublevel:
      - name: Licht
        keywords:
        - keyword: resources/Deckenlicht.pmdl
          actions:
            echo: Schlafzimmer- Deckenlicht selected!
            sublevel:
            - name: einschalten
              keywords:
              - keyword: resources/einschalten.pmdl
                actions:
                  echo: Deckenlicht eingeschaltet!
            - name: ausschalten
              keywords:
              - keyword: resources/ausschalten.pmdl
                actions:
                  echo: Deckenlicht ausgeschaltet!
