action:
- name: Fernseher_lauter
  actions:
  - keyword: resources/Fernseher_lauter.pmdl
  - endpoint: http://192.168.8.131:5000/api/function/fernseher/lauter
  - httpmethod: GET
  - bodyData: xxx
- name: Fernseher_leiser
  actions:
  - keyword: resources/Fernseher_leiser.pmdl
  - endpoint: http://192.168.8.131:5000/api/function/fernseher/leiser
  - httpmethod: GET
  - bodyData: xxx
